tap "buo/cask-upgrade"
tap "git-duet/tap"

brew "bash"
brew "bash-completion"
brew "chromedriver"
brew "colordiff"
brew "diff-so-fancy"
brew "exa"
brew "git"
brew "git-extras"
brew "grep", args: ["with-default-names"]
brew "heroku"
brew "httpie"
brew "hub"
brew "liquidprompt"
brew "nvm"
brew "pgcli"
brew "postgresql", restart_service: true
brew "rbenv"
brew "rbenv-default-gems"
brew "redis", restart_service: true
brew "ruby-build"
brew "tree"
brew "watchman"
brew "wget"
brew "yarn"

cask "alfred"
cask "bartender"
cask "cloak"
cask "dash"
cask "dropbox"
cask "firefox"
cask "fluid"
cask "google-chrome"
cask "insomnia"
cask "licecap"
cask "qlmarkdown"
cask "rocket"
cask "screenhero"
cask "spotify"
cask "zeplin"
